spring.application.name=split-aggregate
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.apache.camel=INFO
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=5
spring.jpa.properties.hibernate.order_inserts=true
camel.component.jpa.join-transaction=false
camel.component.jpa.shared-entity-manager=true