spring.application.name=split-aggregate
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
spring.jpa.properties.hibernate.generate_statistics=true
camel.component.jpa.join-transaction=false
camel.component.jpa.shared-entity-manager=true